### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by shashankkaran** [Faces-Webteam/NITJSR-Faces-Hacktoberfest#1]
Create Navbar as shown in this design : https://www.figma.com/file/KKRW4CkUinOpAYgvEkMJ6V/Untitled?node-id=0%3A1

**Comment by heisdinesh** [comment]
can i work on this @shashankkaran

**Comment by shashankkaran** [comment]
> can i work on this @shashankkaran

Yeah Sure ! 
@heisdinesh

**Comment by heisdinesh** [comment]
@shashankkaran I have given a pull request, and Hacktoberfest website says the repo is not participating in Hacktoberfest could you check this once. thank you

**Comment by shashankkaran** [comment]
> @shashankkaran I have given a pull request, and Hacktoberfest website says the repo is not participating in Hacktoberfest could you check this once. thank you
@heisdinesh 
Navbar wasn't responsive , for a successful PR i have to close the issue with tag 'hactoberfestt-accepted' but due to the quality of PR i cant merge and close the PR successfully

**Comment by Sandhu-Sahil** [comment]
I want to work on this issue
Can you assign this to me, as I see the previous changes are reverted 
@shashankkaran

**Comment by shashankkaran** [comment]
@Sandhu-Sahil Okay!

**Comment by Sandhu-Sahil** [comment]
@shashankkaran I have created a pull request, Please once address it

**Comment by shashankkaran** [comment]
> @shashankkaran I have created a pull request, Please once address it

Perfect !

**Comment by Sandhu-Sahil** [comment]
@shashankkaran thankyou sir
